# Generated by Django 4.2.7 on 2024-03-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50, verbose_name='نام فرستنده')),
                ('text', models.TextField(max_length=500, verbose_name='نظر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.products')),
            ],
        ),
    ]
