# Generated by Django 4.2.7 on 2024-03-15 16:21

import Index.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=Index.models.get_default_id, on_delete=django.db.models.deletion.CASCADE, to='Index.products'),
        ),
    ]
